config/routes.rb
Rails.application.routes.draw do

resources :personnes, only: [ :index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personne.rb
class Personne < ApplicationRecord
    validates_presence_of :prenom, :nom, :profession, :telephone, :adresse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController

    def index
        @personne = Personne.all
    end


    def show
        @personne = Personne.find(params[:id])
    end

    def new
        @personne = Personne.new
    end

    def edit
        @personne = Personne.find(params[:id])
    end

    def create
        @personne = Personne.new(personne_params)
        if @personne.save
            flash[:success] = 'Personne successfully created'
            redirect_to @personne
        else
            flash[:error] = "Opération non aboutie: #{@personne.errors.messages}"
            render :new
        end
    end

    def update
        @personne = Personne.find(params[:id])
        if @personne.update(personne_params)
          flash[:success] = 'Personne successfully OK'
          redirect_to personne_path(@personne)
        end
    end

    def destroy
        @personne = Personne.find(params[:id])
        @personne.destroy
        flash[:success] = 'Suppression successfully OK'
        redirect_to personnes_path
    end

    private
    def personne_params
        params.require(:personne).permit(:prenom, :nom, :profession, :telephone, :adresse)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carnet_helper.rb
module CarnetHelper
end

app/helpers/personne_helper.rb
module PersonneHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carnet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <%= render partial: 'layouts/flash' %>
  <br>
    <%= yield %>
  </body>
</html>

app/views/personnes/edit.html.erb
<h1> Modifier les coordonnées du joueur <h1>
<%= form_with model: @personne, local: true do |form| %>
    <p>
        <%= form.label :prenom %>
        <%= form.text_field :prenom %>
    </p>
     <p>
        <%= form.label :nom %>
        <%= form.text_field :nom %>
    </p>
     <p>
        <%= form.label :profession %>
        <%= form.text_field :profession %>
    </p>
     <p>
        <%= form.label :telephone %>
        <%= form.text_field :telephone %>
    </p>
     <p>
        <%= form.label :adresse %>
        <%= form.text_field :adresse %>
    </p>

    <p>
        <%= form.submit "Modifier le Joueur" %>
    </p>

<% end %>
    

app/views/personnes/index.html.erb
<br>

<h1> Listing des JOUEURS </h1>

<div> 
    <% @personne.each do |personne| %>
        <hr>
        <p>Prénom : <%= personne.prenom %> </p>
        <p>Nom : <%= personne.nom %> </p>
        <p>Profession : <%= personne.profession %> </p>
        <p>telephone : <%= personne.telephone %> </p> 
        <p>adresse : <%= personne.adresse %> </p>
            <p> <%= link_to "Voir joueur", personne_path(personne) %> </p>
            <p> <%= link_to "Nouveau joueur", new_personne_path(personne) %> </p>
            <p> <%= link_to "Modifier joueur", edit_personne_path(personne) %> </p>
            <p> <%= link_to "Supprimer joueur", personne_path(personne), method: :delete %> </p>

    <% end %>
</div>

app/views/personnes/new.html.erb
<br>
<h2> Inscrire un nouveau joueur <h2>

<%= form_with model: @personne, local: true do |form| %>
    <p>
        <%= form.label :prenom %>
        <%= form.text_field :prenom %>
    </p>
     <p>
        <%= form.label :nom %>
        <%= form.text_field :nom %>
    </p>
     <p>
        <%= form.label :profession %>
        <%= form.text_field :profession %>
    </p>
     <p>
        <%= form.label :telephone %>
        <%= form.text_field :telephone %>
    </p>
     <p>
        <%= form.label :adresse %>
        <%= form.text_field :adresse %>
    </p>

    <p>
        <%= form.submit "Créer le Joueur" %>
    </p>


    <% end %>
    

app/views/personnes/show.html.erb
<h1>MR : <%= @personne.prenom %> <%= @personne.nom %> </h1>
    
<div>
    <p>Prénom : <%= @personne.prenom %></p>
    <p>Nom : <%= @personne.nom %></p>
    <p>Profession : <%= @personne.profession %></p>
    <p>telephone : <%= @personne.telephone %></p>
    <p>adresse : <%= @personne.adresse %></p>
    <p><%= link_to "index des joueurs", personnes_path %></p>
</div>